Feat/timepage
swjb-sinamon/sinamon-frontend-v2 pull request #9
Opened 2021-08-09 06:30 UTC by hmc1206

## 😎 어떤 기능이 추가되거나 변경되었나요?
타임페이지 추가

## ❗ 주의하거나 참고할 점이 있나요?

2021-08-09 09:07 UTC, SkyLightQP requested changes
리뷰 확인하고
ESLint, Prettier 적용해주세요

2021-08-09 09:07 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +        {/* <MoreButton to="/" /> */}
필요없는 주석 삭제해주세요.

2021-08-09 09:07 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +      <Gap gap={32} />
필요없는 Gap 삭제

2021-08-09 09:07 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +  height: 300px;
높이 안 줘도 될 것 같습니다

2021-08-09 09:07 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +      <Label>* 수정과에서는 시간표 오류에 따른 책임을 지지 않습니다.</Label>
`Label` 말고 별도 텍스트로 처리해주세요
색깔은 `var(--color-subtext)` 사용

2021-08-09 09:07 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +      <Label>* 4시간 주기로 시간표를 새로고침합니다.</Label>
여기도

2021-08-09 09:07 UTC, SkyLightQP commented on src/components/TimetableCard/Timepage.tsx
> +const TimetableCard: React.FC<TimetableCardProps> = ({ day, children }) => {
기존에 있는 컴포넌트하고 이름 같습니다. 코드 바뀐게 없는 거 같은데
이 컴포넌트는 삭제하고 기존 `TimetableCard` 컴포넌트 써도 될 거 같아요

2021-08-09 09:07 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +const Timepage: React.FC = () => {
파일 이름, 페이지 이름 `Timepage`말고 **`TimetablePage`** 로

2021-08-09 10:45 UTC, hmc1206 commented on src/pages/TimePage.tsx
> +const Timepage: React.FC = () => {
😎 어떤 기능이 추가되거나 변경되었나요?
리뷰 반영

❗ 주의하거나 참고할 점이 있나요?

2021-08-09 10:53 UTC, SkyLightQP requested changes

2021-08-09 10:53 UTC, SkyLightQP commented on src/Router.tsx
> +import Timepage from './pages/TimetablePage';
`Timepage` -> `TimetablePage`

2021-08-09 10:53 UTC, SkyLightQP commented on src/Router.tsx
> +        path="/Time"
URL에는 대문자 쓰지 않음
`Time` -> `timetable`

2021-08-09 10:53 UTC, SkyLightQP commented on src/Router.tsx
> +        failure={() => RedirectLogin('/Time')}
여기도 timetable 으로

2021-08-09 10:53 UTC, SkyLightQP commented on src/Router.tsx
> +        success={() => Timepage}
`TimetablePage`

2021-08-09 10:53 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +const Timetablepage: React.FC = () => {
`TimetablePage` 로 변경 (파일 이름, 클래스명, 컴포넌트는 PascalCase 사용)
파일 이름도 TimetablePage.tsx 로 변경

2021-08-09 10:53 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +      <ContentHeader>
의미없는 스타일. 지워도 될듯

2021-08-09 10:53 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +const Text = styled.div`
텍스트는 p 태그 사용

2021-08-09 10:53 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +  color : var(--color-subtext);
CSS 스타일
`color: var(생략);` 으로 수정

2021-08-09 11:51 UTC, hmc1206 commented on src/pages/TimePage.tsx
> +  color : var(--color-subtext);
😎 어떤 기능이 추가되거나 변경되었나요?
리뷰 반영2

❗ 주의하거나 참고할 점이 있나요?

2021-08-09 13:10 UTC, SkyLightQP requested changes
+)
과목별 담당선생님 이름도 함께 표시해주세요
`time.teacher` 로 표시 가능

2021-08-09 13:10 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +const p = styled.div`
변수 이름이 아니라 HTML 태그를 `p`로 바꿔주세요

2021-08-09 13:10 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +  color : var(생략);
실제 컬러 값 적용해주세요 `--color-subtext`

2021-08-09 13:10 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +      <p>* 수정과에서는 시간표 오류에 따른 책임을 지지 않습니다.</p>
여기도 위 변수 이름에 맞춰 변경

2021-08-09 13:10 UTC, SkyLightQP commented on src/pages/TimePage.tsx
> +const TimetablePage: React.FC = () => {
파일 이름 `TimetablePage.tsx` 로 바꿔주세요.

2021-08-09 13:12 UTC, SkyLightQP commented
커밋 컨벤션 꼭 맞춰주고
리뷰 반영 후에 반영했다고 댓글 안 달아도 돼요 저한테 알림옴

2021-08-11 09:03 UTC, SkyLightQP approved these changes

2021-08-11 09:03 UTC, merged